#!/usr/bin/env python3
"""
Script to generate manifest.json files for all sections.
Run this script whenever you add new folders to the Sections directory.
Also creates a manifest-loader.js file that can be included in gallery.html
"""

import json
from pathlib import Path

def generate_manifests():
    sections_dir = Path("Sections")
    
    if not sections_dir.exists():
        print("Sections directory not found!")
        return
    
    all_manifests = {}
    
    for section_dir in sorted(sections_dir.iterdir()):
        if section_dir.is_dir():
            manifest_file = section_dir / "manifest.json"
            items = []
            
            # Recursively find all subdirectories with code.html
            for item_dir in sorted(section_dir.rglob("*")):
                if item_dir.is_dir():
                    html_file = item_dir / "code.html"
                    # Try different image extensions
                    img_file = None
                    for ext in [".png", ".jpg", ".jpeg", ".webp"]:
                        test_file = item_dir / f"screen{ext}"
                        if test_file.exists():
                            img_file = test_file
                            break
                    
                    if html_file.exists() and img_file:
                        # Use relative paths from root
                        rel_folder = str(item_dir.relative_to(Path(".")))
                        rel_html = str(html_file.relative_to(Path(".")))
                        rel_thumbnail = str(img_file.relative_to(Path(".")))
                        
                        items.append({
                            "folder": rel_folder,
                            "name": item_dir.name,
                            "html": rel_html,
                            "thumbnail": rel_thumbnail
                        })
            
            if items:
                manifest = {"items": items}
                with open(manifest_file, 'w') as f:
                    json.dump(manifest, f, indent=2)
                print(f"✓ Generated manifest for '{section_dir.name}' with {len(items)} items")
                
                # Store for creating loader file
                folder_path = str(section_dir.relative_to(Path(".")))
                all_manifests[folder_path] = manifest
            else:
                print(f"⚠ No items found in '{section_dir.name}'")
    
    # Create a JavaScript file with all manifests embedded
    create_manifest_loader(all_manifests)
    
    return all_manifests

def create_manifest_loader(all_manifests):
    """Create a JavaScript file with all manifests embedded"""
    loader_file = Path("manifest-loader.js")
    
    # Create JavaScript object with all manifests
    js_content = "// Auto-generated manifest data - works with file:// protocol\n"
    js_content += "// This file is generated by generate-manifests.py\n\n"
    js_content += "const allManifests = " + json.dumps(all_manifests, indent=2) + ";\n\n"
    js_content += """// Function to get manifest for a section folder
function getManifestForSection(sectionFolder) {
    // Normalize path (handle both forward and backslashes)
    const normalized = sectionFolder.replace(/\\\\/g, '/');
    return allManifests[normalized] || null;
}
"""
    
    with open(loader_file, 'w') as f:
        f.write(js_content)
    
    print(f"✓ Created manifest-loader.js with {len(all_manifests)} section manifests")

if __name__ == "__main__":
    generate_manifests()
    print("\nDone! Manifests have been generated.")
