// Auto-generated manifest data - works with file:// protocol
// This file is generated by generate-manifests.py

const allManifests = {
  "Sections/Admin Dashboard": {
    "items": [
      {
        "folder": "Sections/Admin Dashboard/admin_dashboard,_variant_1_of_3",
        "name": "admin_dashboard,_variant_1_of_3",
        "html": "Sections/Admin Dashboard/admin_dashboard,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Admin Dashboard/admin_dashboard,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Admin Dashboard/admin_dashboard,_variant_2_of_3",
        "name": "admin_dashboard,_variant_2_of_3",
        "html": "Sections/Admin Dashboard/admin_dashboard,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Admin Dashboard/admin_dashboard,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Admin Dashboard/admin_dashboard,_variant_3_of_3",
        "name": "admin_dashboard,_variant_3_of_3",
        "html": "Sections/Admin Dashboard/admin_dashboard,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Admin Dashboard/admin_dashboard,_variant_3_of_3/screen.png"
      }
    ]
  },
  "Sections/Browse Merch": {
    "items": [
      {
        "folder": "Sections/Browse Merch/merch_store_home,_variant_1_of_3",
        "name": "merch_store_home,_variant_1_of_3",
        "html": "Sections/Browse Merch/merch_store_home,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Browse Merch/merch_store_home,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Browse Merch/merch_store_home,_variant_2_of_3",
        "name": "merch_store_home,_variant_2_of_3",
        "html": "Sections/Browse Merch/merch_store_home,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Browse Merch/merch_store_home,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Browse Merch/merch_store_home,_variant_3_of_3",
        "name": "merch_store_home,_variant_3_of_3",
        "html": "Sections/Browse Merch/merch_store_home,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Browse Merch/merch_store_home,_variant_3_of_3/screen.png"
      }
    ]
  },
  "Sections/Checkout & Order Info": {
    "items": [
      {
        "folder": "Sections/Checkout & Order Info/checkout_(payment_information)",
        "name": "checkout_(payment_information)",
        "html": "Sections/Checkout & Order Info/checkout_(payment_information)/code.html",
        "thumbnail": "Sections/Checkout & Order Info/checkout_(payment_information)/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/checkout_(shipping_information)",
        "name": "checkout_(shipping_information)",
        "html": "Sections/Checkout & Order Info/checkout_(shipping_information)/code.html",
        "thumbnail": "Sections/Checkout & Order Info/checkout_(shipping_information)/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/order_details,_variant_1_of_3",
        "name": "order_details,_variant_1_of_3",
        "html": "Sections/Checkout & Order Info/order_details,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Checkout & Order Info/order_details,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/order_details,_variant_2_of_3",
        "name": "order_details,_variant_2_of_3",
        "html": "Sections/Checkout & Order Info/order_details,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Checkout & Order Info/order_details,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/order_details,_variant_3_of_3",
        "name": "order_details,_variant_3_of_3",
        "html": "Sections/Checkout & Order Info/order_details,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Checkout & Order Info/order_details,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/order_history",
        "name": "order_history",
        "html": "Sections/Checkout & Order Info/order_history/code.html",
        "thumbnail": "Sections/Checkout & Order Info/order_history/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/shopping_cart,_variant_1_of_3",
        "name": "shopping_cart,_variant_1_of_3",
        "html": "Sections/Checkout & Order Info/shopping_cart,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Checkout & Order Info/shopping_cart,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/shopping_cart,_variant_2_of_3",
        "name": "shopping_cart,_variant_2_of_3",
        "html": "Sections/Checkout & Order Info/shopping_cart,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Checkout & Order Info/shopping_cart,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Checkout & Order Info/shopping_cart,_variant_3_of_3",
        "name": "shopping_cart,_variant_3_of_3",
        "html": "Sections/Checkout & Order Info/shopping_cart,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Checkout & Order Info/shopping_cart,_variant_3_of_3/screen.png"
      }
    ]
  },
  "Sections/Events": {
    "items": [
      {
        "folder": "Sections/Events/event_calendar",
        "name": "event_calendar",
        "html": "Sections/Events/event_calendar/code.html",
        "thumbnail": "Sections/Events/event_calendar/screen.png"
      },
      {
        "folder": "Sections/Events/event_detail_page",
        "name": "event_detail_page",
        "html": "Sections/Events/event_detail_page/code.html",
        "thumbnail": "Sections/Events/event_detail_page/screen.png"
      },
      {
        "folder": "Sections/Events/events_calendar,_variant_1_of_3",
        "name": "events_calendar,_variant_1_of_3",
        "html": "Sections/Events/events_calendar,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Events/events_calendar,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Events/events_calendar,_variant_2_of_3",
        "name": "events_calendar,_variant_2_of_3",
        "html": "Sections/Events/events_calendar,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Events/events_calendar,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Events/events_calendar,_variant_3_of_3",
        "name": "events_calendar,_variant_3_of_3",
        "html": "Sections/Events/events_calendar,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Events/events_calendar,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/Events/my_events,_variant_1_of_3",
        "name": "my_events,_variant_1_of_3",
        "html": "Sections/Events/my_events,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Events/my_events,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Events/my_events,_variant_2_of_3",
        "name": "my_events,_variant_2_of_3",
        "html": "Sections/Events/my_events,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Events/my_events,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Events/my_events,_variant_3_of_3",
        "name": "my_events,_variant_3_of_3",
        "html": "Sections/Events/my_events,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Events/my_events,_variant_3_of_3/screen.png"
      }
    ]
  },
  "Sections/Home Dashboard": {
    "items": [
      {
        "folder": "Sections/Home Dashboard/guest_home,_variant_1_of_3",
        "name": "guest_home,_variant_1_of_3",
        "html": "Sections/Home Dashboard/guest_home,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Home Dashboard/guest_home,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Home Dashboard/guest_home,_variant_2_of_3",
        "name": "guest_home,_variant_2_of_3",
        "html": "Sections/Home Dashboard/guest_home,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Home Dashboard/guest_home,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Home Dashboard/guest_home,_variant_3_of_3",
        "name": "guest_home,_variant_3_of_3",
        "html": "Sections/Home Dashboard/guest_home,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Home Dashboard/guest_home,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/Home Dashboard/home_dashboard",
        "name": "home_dashboard",
        "html": "Sections/Home Dashboard/home_dashboard/code.html",
        "thumbnail": "Sections/Home Dashboard/home_dashboard/screen.png"
      },
      {
        "folder": "Sections/Home Dashboard/user_home_dashboard",
        "name": "user_home_dashboard",
        "html": "Sections/Home Dashboard/user_home_dashboard/code.html",
        "thumbnail": "Sections/Home Dashboard/user_home_dashboard/screen.png"
      }
    ]
  },
  "Sections/Onboarding": {
    "items": [
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_1_of_3",
        "name": "onboarding_screen,_variant_1_of_3",
        "html": "Sections/Onboarding/onboarding_screen,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_2_of_3",
        "name": "onboarding_screen,_variant_2_of_3",
        "html": "Sections/Onboarding/onboarding_screen,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_1",
        "name": "onboarding_screen,_variant_3_of_3_1",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_1/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_1/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_2",
        "name": "onboarding_screen,_variant_3_of_3_2",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_2/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_2/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_3",
        "name": "onboarding_screen,_variant_3_of_3_3",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_3/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_3/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_4",
        "name": "onboarding_screen,_variant_3_of_3_4",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_4/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_4/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_5",
        "name": "onboarding_screen,_variant_3_of_3_5",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_5/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_5/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_6",
        "name": "onboarding_screen,_variant_3_of_3_6",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_6/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_6/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_7",
        "name": "onboarding_screen,_variant_3_of_3_7",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_7/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_7/screen.png"
      },
      {
        "folder": "Sections/Onboarding/welcome/onboarding_screen_1",
        "name": "onboarding_screen_1",
        "html": "Sections/Onboarding/welcome/onboarding_screen_1/code.html",
        "thumbnail": "Sections/Onboarding/welcome/onboarding_screen_1/screen.png"
      }
    ]
  },
  "Sections/Product Gallery": {
    "items": [
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_1",
        "name": "cannabis_nug_product_library,_variant_1_of_3_1",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_1/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_1/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_2",
        "name": "cannabis_nug_product_library,_variant_1_of_3_2",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_2/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_2/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_3",
        "name": "cannabis_nug_product_library,_variant_1_of_3_3",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_3/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_3/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_2_of_3",
        "name": "cannabis_nug_product_library,_variant_2_of_3",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_3_of_3",
        "name": "cannabis_nug_product_library,_variant_3_of_3",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/favorites_/_saved_products",
        "name": "_saved_products",
        "html": "Sections/Product Gallery/favorites_/_saved_products/code.html",
        "thumbnail": "Sections/Product Gallery/favorites_/_saved_products/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/product_library",
        "name": "product_library",
        "html": "Sections/Product Gallery/product_library/code.html",
        "thumbnail": "Sections/Product Gallery/product_library/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/product_library_(full_access)_-_user",
        "name": "product_library_(full_access)_-_user",
        "html": "Sections/Product Gallery/product_library_(full_access)_-_user/code.html",
        "thumbnail": "Sections/Product Gallery/product_library_(full_access)_-_user/screen.png"
      }
    ]
  },
  "Sections/Reward System": {
    "items": [
      {
        "folder": "Sections/Reward System/fraud_prevention_notices",
        "name": "fraud_prevention_notices",
        "html": "Sections/Reward System/fraud_prevention_notices/code.html",
        "thumbnail": "Sections/Reward System/fraud_prevention_notices/screen.png"
      },
      {
        "folder": "Sections/Reward System/gamified_education_screen",
        "name": "gamified_education_screen",
        "html": "Sections/Reward System/gamified_education_screen/code.html",
        "thumbnail": "Sections/Reward System/gamified_education_screen/screen.png"
      },
      {
        "folder": "Sections/Reward System/how_to_earn_points",
        "name": "how_to_earn_points",
        "html": "Sections/Reward System/how_to_earn_points/code.html",
        "thumbnail": "Sections/Reward System/how_to_earn_points/screen.png"
      },
      {
        "folder": "Sections/Reward System/missions_dashboard",
        "name": "missions_dashboard",
        "html": "Sections/Reward System/missions_dashboard/code.html",
        "thumbnail": "Sections/Reward System/missions_dashboard/screen.png"
      },
      {
        "folder": "Sections/Reward System/points_dashboard",
        "name": "points_dashboard",
        "html": "Sections/Reward System/points_dashboard/code.html",
        "thumbnail": "Sections/Reward System/points_dashboard/screen.png"
      },
      {
        "folder": "Sections/Reward System/reward_detail_page",
        "name": "reward_detail_page",
        "html": "Sections/Reward System/reward_detail_page/code.html",
        "thumbnail": "Sections/Reward System/reward_detail_page/screen.png"
      },
      {
        "folder": "Sections/Reward System/rewards_catalog",
        "name": "rewards_catalog",
        "html": "Sections/Reward System/rewards_catalog/code.html",
        "thumbnail": "Sections/Reward System/rewards_catalog/screen.png"
      }
    ]
  },
  "Sections/Website Home page guest": {
    "items": [
      {
        "folder": "Sections/Website Home page guest/guest_home_landing_page,_variant_1_of_3",
        "name": "guest_home_landing_page,_variant_1_of_3",
        "html": "Sections/Website Home page guest/guest_home_landing_page,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Website Home page guest/guest_home_landing_page,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Website Home page guest/guest_home_landing_page,_variant_2_of_3",
        "name": "guest_home_landing_page,_variant_2_of_3",
        "html": "Sections/Website Home page guest/guest_home_landing_page,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Website Home page guest/guest_home_landing_page,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Website Home page guest/guest_home_landing_page,_variant_3_of_3",
        "name": "guest_home_landing_page,_variant_3_of_3",
        "html": "Sections/Website Home page guest/guest_home_landing_page,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Website Home page guest/guest_home_landing_page,_variant_3_of_3/screen.png"
      }
    ]
  },
  "Sections/Where to Buy": {
    "items": [
      {
        "folder": "Sections/Where to Buy/map_/_find_dispensaries_(user_mode)_",
        "name": "_find_dispensaries_(user_mode)_",
        "html": "Sections/Where to Buy/map_/_find_dispensaries_(user_mode)_/code.html",
        "thumbnail": "Sections/Where to Buy/map_/_find_dispensaries_(user_mode)_/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_1",
        "name": "where_to_buy_map_1",
        "html": "Sections/Where to Buy/where_to_buy_map_1/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_1/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_10",
        "name": "where_to_buy_map_10",
        "html": "Sections/Where to Buy/where_to_buy_map_10/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_10/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_11",
        "name": "where_to_buy_map_11",
        "html": "Sections/Where to Buy/where_to_buy_map_11/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_11/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_12",
        "name": "where_to_buy_map_12",
        "html": "Sections/Where to Buy/where_to_buy_map_12/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_12/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_13",
        "name": "where_to_buy_map_13",
        "html": "Sections/Where to Buy/where_to_buy_map_13/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_13/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_14",
        "name": "where_to_buy_map_14",
        "html": "Sections/Where to Buy/where_to_buy_map_14/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_14/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_2",
        "name": "where_to_buy_map_2",
        "html": "Sections/Where to Buy/where_to_buy_map_2/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_2/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_3",
        "name": "where_to_buy_map_3",
        "html": "Sections/Where to Buy/where_to_buy_map_3/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_3/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_4",
        "name": "where_to_buy_map_4",
        "html": "Sections/Where to Buy/where_to_buy_map_4/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_4/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_5",
        "name": "where_to_buy_map_5",
        "html": "Sections/Where to Buy/where_to_buy_map_5/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_5/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_6",
        "name": "where_to_buy_map_6",
        "html": "Sections/Where to Buy/where_to_buy_map_6/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_6/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_7",
        "name": "where_to_buy_map_7",
        "html": "Sections/Where to Buy/where_to_buy_map_7/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_7/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_8",
        "name": "where_to_buy_map_8",
        "html": "Sections/Where to Buy/where_to_buy_map_8/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_8/screen.png"
      },
      {
        "folder": "Sections/Where to Buy/where_to_buy_map_9",
        "name": "where_to_buy_map_9",
        "html": "Sections/Where to Buy/where_to_buy_map_9/code.html",
        "thumbnail": "Sections/Where to Buy/where_to_buy_map_9/screen.png"
      }
    ]
  },
  "Sections/account settings": {
    "items": [
      {
        "folder": "Sections/account settings/account_settings,_variant_1_of_3",
        "name": "account_settings,_variant_1_of_3",
        "html": "Sections/account settings/account_settings,_variant_1_of_3/code.html",
        "thumbnail": "Sections/account settings/account_settings,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/account_settings,_variant_2_of_3",
        "name": "account_settings,_variant_2_of_3",
        "html": "Sections/account settings/account_settings,_variant_2_of_3/code.html",
        "thumbnail": "Sections/account settings/account_settings,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/account_settings,_variant_3_of_3",
        "name": "account_settings,_variant_3_of_3",
        "html": "Sections/account settings/account_settings,_variant_3_of_3/code.html",
        "thumbnail": "Sections/account settings/account_settings,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/help_&_support",
        "name": "help_&_support",
        "html": "Sections/account settings/help_&_support/code.html",
        "thumbnail": "Sections/account settings/help_&_support/screen.png"
      },
      {
        "folder": "Sections/account settings/notification_settings",
        "name": "notification_settings",
        "html": "Sections/account settings/notification_settings/code.html",
        "thumbnail": "Sections/account settings/notification_settings/screen.png"
      },
      {
        "folder": "Sections/account settings/notifications_list,_variant_1_of_3",
        "name": "notifications_list,_variant_1_of_3",
        "html": "Sections/account settings/notifications_list,_variant_1_of_3/code.html",
        "thumbnail": "Sections/account settings/notifications_list,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/notifications_list,_variant_2_of_3",
        "name": "notifications_list,_variant_2_of_3",
        "html": "Sections/account settings/notifications_list,_variant_2_of_3/code.html",
        "thumbnail": "Sections/account settings/notifications_list,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/notifications_list,_variant_3_of_3",
        "name": "notifications_list,_variant_3_of_3",
        "html": "Sections/account settings/notifications_list,_variant_3_of_3/code.html",
        "thumbnail": "Sections/account settings/notifications_list,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/preferences,_variant_1_of_3",
        "name": "preferences,_variant_1_of_3",
        "html": "Sections/account settings/preferences,_variant_1_of_3/code.html",
        "thumbnail": "Sections/account settings/preferences,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/preferences,_variant_2_of_3",
        "name": "preferences,_variant_2_of_3",
        "html": "Sections/account settings/preferences,_variant_2_of_3/code.html",
        "thumbnail": "Sections/account settings/preferences,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/preferences,_variant_3_of_3",
        "name": "preferences,_variant_3_of_3",
        "html": "Sections/account settings/preferences,_variant_3_of_3/code.html",
        "thumbnail": "Sections/account settings/preferences,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/account settings/profile_overview",
        "name": "profile_overview",
        "html": "Sections/account settings/profile_overview/code.html",
        "thumbnail": "Sections/account settings/profile_overview/screen.png"
      }
    ]
  },
  "Sections/education": {
    "items": [
      {
        "folder": "Sections/education/course_library,_variant_1_of_3",
        "name": "course_library,_variant_1_of_3",
        "html": "Sections/education/course_library,_variant_1_of_3/code.html",
        "thumbnail": "Sections/education/course_library,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/education/course_library,_variant_2_of_3",
        "name": "course_library,_variant_2_of_3",
        "html": "Sections/education/course_library,_variant_2_of_3/code.html",
        "thumbnail": "Sections/education/course_library,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/education/course_library,_variant_3_of_3",
        "name": "course_library,_variant_3_of_3",
        "html": "Sections/education/course_library,_variant_3_of_3/code.html",
        "thumbnail": "Sections/education/course_library,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/education/education_dashboard,_variant_1_of_3",
        "name": "education_dashboard,_variant_1_of_3",
        "html": "Sections/education/education_dashboard,_variant_1_of_3/code.html",
        "thumbnail": "Sections/education/education_dashboard,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/education/education_dashboard,_variant_2_of_3",
        "name": "education_dashboard,_variant_2_of_3",
        "html": "Sections/education/education_dashboard,_variant_2_of_3/code.html",
        "thumbnail": "Sections/education/education_dashboard,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/education/education_dashboard,_variant_3_of_3",
        "name": "education_dashboard,_variant_3_of_3",
        "html": "Sections/education/education_dashboard,_variant_3_of_3/code.html",
        "thumbnail": "Sections/education/education_dashboard,_variant_3_of_3/screen.png"
      }
    ]
  },
  "Sections/merch item page": {
    "items": [
      {
        "folder": "Sections/merch item page/merch_store_product_detail_1",
        "name": "merch_store_product_detail_1",
        "html": "Sections/merch item page/merch_store_product_detail_1/code.html",
        "thumbnail": "Sections/merch item page/merch_store_product_detail_1/screen.png"
      },
      {
        "folder": "Sections/merch item page/merch_store_product_detail_2",
        "name": "merch_store_product_detail_2",
        "html": "Sections/merch item page/merch_store_product_detail_2/code.html",
        "thumbnail": "Sections/merch item page/merch_store_product_detail_2/screen.png"
      },
      {
        "folder": "Sections/merch item page/merch_store_product_detail_3",
        "name": "merch_store_product_detail_3",
        "html": "Sections/merch item page/merch_store_product_detail_3/code.html",
        "thumbnail": "Sections/merch item page/merch_store_product_detail_3/screen.png"
      },
      {
        "folder": "Sections/merch item page/merch_store_product_detail_4",
        "name": "merch_store_product_detail_4",
        "html": "Sections/merch item page/merch_store_product_detail_4/code.html",
        "thumbnail": "Sections/merch item page/merch_store_product_detail_4/screen.png"
      }
    ]
  },
  "Sections/product details": {
    "items": [
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_1",
        "name": "individual_strain_page,_variant_1_of_3_1",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_1/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_2",
        "name": "individual_strain_page,_variant_1_of_3_2",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_2/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_3",
        "name": "individual_strain_page,_variant_1_of_3_3",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_3/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_3/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_4",
        "name": "individual_strain_page,_variant_1_of_3_4",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_4/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_4/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_5",
        "name": "individual_strain_page,_variant_1_of_3_5",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_5/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_5/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_2_of_3_1",
        "name": "individual_strain_page,_variant_2_of_3_1",
        "html": "Sections/product details/individual_strain_page,_variant_2_of_3_1/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_2_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_2_of_3_2",
        "name": "individual_strain_page,_variant_2_of_3_2",
        "html": "Sections/product details/individual_strain_page,_variant_2_of_3_2/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_2_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_3_of_3_1",
        "name": "individual_strain_page,_variant_3_of_3_1",
        "html": "Sections/product details/individual_strain_page,_variant_3_of_3_1/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_3_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_3_of_3_2",
        "name": "individual_strain_page,_variant_3_of_3_2",
        "html": "Sections/product details/individual_strain_page,_variant_3_of_3_2/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_3_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_1_of_3",
        "name": "product_detail_page,_variant_1_of_3",
        "html": "Sections/product details/product_detail_page,_variant_1_of_3/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_2_of_3",
        "name": "product_detail_page,_variant_2_of_3",
        "html": "Sections/product details/product_detail_page,_variant_2_of_3/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_1",
        "name": "product_detail_page,_variant_3_of_3_1",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_1/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_2",
        "name": "product_detail_page,_variant_3_of_3_2",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_2/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_3",
        "name": "product_detail_page,_variant_3_of_3_3",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_3/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_3/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_4",
        "name": "product_detail_page,_variant_3_of_3_4",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_4/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_4/screen.png"
      }
    ]
  }
};

// Function to get manifest for a section folder
function getManifestForSection(sectionFolder) {
    // Normalize path (handle both forward and backslashes)
    const normalized = sectionFolder.replace(/\\/g, '/');
    return allManifests[normalized] || null;
}
