// Auto-generated manifest data - works with file:// protocol
// This file is generated by generate-manifests.py

const allManifests = {
  "Sections/Onboarding": {
    "items": [
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_1_of_3",
        "name": "onboarding_screen,_variant_1_of_3",
        "html": "Sections/Onboarding/onboarding_screen,_variant_1_of_3/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_2_of_3",
        "name": "onboarding_screen,_variant_2_of_3",
        "html": "Sections/Onboarding/onboarding_screen,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_1",
        "name": "onboarding_screen,_variant_3_of_3_1",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_1/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_1/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_2",
        "name": "onboarding_screen,_variant_3_of_3_2",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_2/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_2/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_3",
        "name": "onboarding_screen,_variant_3_of_3_3",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_3/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_3/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_4",
        "name": "onboarding_screen,_variant_3_of_3_4",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_4/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_4/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_5",
        "name": "onboarding_screen,_variant_3_of_3_5",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_5/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_5/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_6",
        "name": "onboarding_screen,_variant_3_of_3_6",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_6/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_6/screen.png"
      },
      {
        "folder": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_7",
        "name": "onboarding_screen,_variant_3_of_3_7",
        "html": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_7/code.html",
        "thumbnail": "Sections/Onboarding/onboarding_screen,_variant_3_of_3_7/screen.png"
      },
      {
        "folder": "Sections/Onboarding/welcome/onboarding_screen_1",
        "name": "onboarding_screen_1",
        "html": "Sections/Onboarding/welcome/onboarding_screen_1/code.html",
        "thumbnail": "Sections/Onboarding/welcome/onboarding_screen_1/screen.png"
      }
    ]
  },
  "Sections/Product Gallery": {
    "items": [
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_1",
        "name": "cannabis_nug_product_library,_variant_1_of_3_1",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_1/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_1/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_2",
        "name": "cannabis_nug_product_library,_variant_1_of_3_2",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_2/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_2/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_3",
        "name": "cannabis_nug_product_library,_variant_1_of_3_3",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_3/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_1_of_3_3/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_2_of_3",
        "name": "cannabis_nug_product_library,_variant_2_of_3",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_2_of_3/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/cannabis_nug_product_library,_variant_3_of_3",
        "name": "cannabis_nug_product_library,_variant_3_of_3",
        "html": "Sections/Product Gallery/cannabis_nug_product_library,_variant_3_of_3/code.html",
        "thumbnail": "Sections/Product Gallery/cannabis_nug_product_library,_variant_3_of_3/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/favorites_/_saved_products",
        "name": "_saved_products",
        "html": "Sections/Product Gallery/favorites_/_saved_products/code.html",
        "thumbnail": "Sections/Product Gallery/favorites_/_saved_products/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/product_library",
        "name": "product_library",
        "html": "Sections/Product Gallery/product_library/code.html",
        "thumbnail": "Sections/Product Gallery/product_library/screen.png"
      },
      {
        "folder": "Sections/Product Gallery/product_library_(full_access)_-_user",
        "name": "product_library_(full_access)_-_user",
        "html": "Sections/Product Gallery/product_library_(full_access)_-_user/code.html",
        "thumbnail": "Sections/Product Gallery/product_library_(full_access)_-_user/screen.png"
      }
    ]
  },
  "Sections/product details": {
    "items": [
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_1",
        "name": "individual_strain_page,_variant_1_of_3_1",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_1/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_2",
        "name": "individual_strain_page,_variant_1_of_3_2",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_2/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_3",
        "name": "individual_strain_page,_variant_1_of_3_3",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_3/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_3/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_4",
        "name": "individual_strain_page,_variant_1_of_3_4",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_4/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_4/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_1_of_3_5",
        "name": "individual_strain_page,_variant_1_of_3_5",
        "html": "Sections/product details/individual_strain_page,_variant_1_of_3_5/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_1_of_3_5/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_2_of_3_1",
        "name": "individual_strain_page,_variant_2_of_3_1",
        "html": "Sections/product details/individual_strain_page,_variant_2_of_3_1/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_2_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_2_of_3_2",
        "name": "individual_strain_page,_variant_2_of_3_2",
        "html": "Sections/product details/individual_strain_page,_variant_2_of_3_2/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_2_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_3_of_3_1",
        "name": "individual_strain_page,_variant_3_of_3_1",
        "html": "Sections/product details/individual_strain_page,_variant_3_of_3_1/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_3_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/individual_strain_page,_variant_3_of_3_2",
        "name": "individual_strain_page,_variant_3_of_3_2",
        "html": "Sections/product details/individual_strain_page,_variant_3_of_3_2/code.html",
        "thumbnail": "Sections/product details/individual_strain_page,_variant_3_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_1_of_3",
        "name": "product_detail_page,_variant_1_of_3",
        "html": "Sections/product details/product_detail_page,_variant_1_of_3/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_1_of_3/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_2_of_3",
        "name": "product_detail_page,_variant_2_of_3",
        "html": "Sections/product details/product_detail_page,_variant_2_of_3/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_2_of_3/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_1",
        "name": "product_detail_page,_variant_3_of_3_1",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_1/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_1/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_2",
        "name": "product_detail_page,_variant_3_of_3_2",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_2/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_2/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_3",
        "name": "product_detail_page,_variant_3_of_3_3",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_3/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_3/screen.png"
      },
      {
        "folder": "Sections/product details/product_detail_page,_variant_3_of_3_4",
        "name": "product_detail_page,_variant_3_of_3_4",
        "html": "Sections/product details/product_detail_page,_variant_3_of_3_4/code.html",
        "thumbnail": "Sections/product details/product_detail_page,_variant_3_of_3_4/screen.png"
      }
    ]
  }
};

// Function to get manifest for a section folder
function getManifestForSection(sectionFolder) {
    // Normalize path (handle both forward and backslashes)
    const normalized = sectionFolder.replace(/\\/g, '/');
    return allManifests[normalized] || null;
}
